site_name: Max Raphael Project
site_description: To commemorate the work of art historian and philosopher Max Raphael
site_url: http://www.maxraphael.org

theme:
    name: 'material'
    custom_dir: 'material'
    favicon: 'library_books'
    logo: assets/contour.gif
markdown_extensions:
    - admonition
    - footnotes
    - meta
    - toc:
        permalink: true

repo_name: 'max-raphael-project'
repo_url: 'https://github.com/sammeltassen/mkdocs-base'

copyright: 'Copyright &copy; 2016 - 2018 The Max Raphael Project'
  
pages:
    - Home: index.md
    - Biography: biography.md
    - Bibliography:
        - Primary sources: bibliography/primary.md
        - Secondary sources: bibliography/secondary.md
    - Resources:
        - Max Raphael's (Auto)biography: resources/autobiography.md
        - Shirley Chesney on Max Raphael: resources/chesney.md
    - Project:
        - About: project/about.md
        - Contributors: project/contributors.md
        - Contact: project/contact.md