site_name: The Max Raphael Project
site_description: To commemorate the work of art historian and philosopher Max Raphael
site_url: http://www.maxraphael.org

theme:
    name: 'material'
    custom_dir: 'material'
    favicon: /assets/favicon.png
    logo:
        icon: 'library_books'
    silhouette: /assets/silhouette_black.png
    palette:
        primary: 'indigo'
        accent: 'indigo'
        
markdown_extensions:
    - admonition
    - footnotes
    - meta
    - toc:
        permalink: true
    - pymdownx.critic
    - pymdownx.tilde
    - pymdownx.mark

extra_css:
  - '/assets/css/magnific-popup.css'

repo_name: 'max-raphael-project'
repo_url: 'https://github.com/sammeltassen/mkdocs-base'

copyright: 'Copyright &copy; 2011 - 2018 The Max Raphael Project and the respective authors'

google_analytics:
  - 'UA-119145714-1'
  - 'auto'
  
pages:
    - Home: index.md
    - Biography: biography.md
    - Bibliography: bibliography.md
    - Resources:
        - Max Raphael's (auto)biography: resources/autobiography.md
        - Shirley Chesney on Max Raphael: resources/chesney.md
        - Cezanne: resources/healy.md
    - Contributors: project/contributors.md
    - Contact: project/contact.md