site_name: Max Raphael Project
site_description: To commemorate the work of art historian and philosopher Max Raphael
site_url: http://www.maxraphael.org

theme:
    name: 'material'
    custom_dir: 'material'
    favicon: assets/favicon.png
    logo: assets/silhouette.png
    palette:
        primary: 'brown'
        accent: 'indigo'
        
markdown_extensions:
    - admonition
    - footnotes
    - meta
    - toc:
        permalink: true

repo_name: 'max-raphael-project'
repo_url: 'https://github.com/sammeltassen/mkdocs-base'

copyright: 'Copyright &copy; 2016 - 2018 The Max Raphael Project'
  
pages:
    - Home: index.md
    - Biography: biography.md
    - Bibliography: bibliography.md
    - Resources:
        - Max Raphael's (auto)biography: resources/autobiography.md
        - Shirley Chesney on Max Raphael: resources/chesney.md
    - Contributors: project/contributors.md
    - Contact: project/contact.md